### ISSUE TITLE
KIM Spec hat sich im HotFix um 180° gedreht

### ISSUE THREAD

**Issue by dhufnagel** [sberg-net/openkim#4]
https://github.com/sberg-net/openkim/blob/af5bc4a453efb2467a0c46f8f7d2b461353b713d/src/main/java/net/sberg/openkim/kas/KasService.java#L128

Achtung, leider hat sich die KIM Spec aus mir unerfindlichen Gründen stark geändert, sodass nicht mehr einzelne Anhänge auf den KAS hochgeladen werden müssen, sondern die komplette E-Mail! Somit muss also der komplette MIME Body verschlüsselt werden. 
Die Dokumentensuche auf dem Fachportal liefert nicht die neuste Hotfix Version, diese findet man nur unter der Downloadübersicht: https://fachportal.gematik.de/schnelleinstieg/downloadcenter/releases#c6557

**Comment by basketmc** [comment]
Hallo Herr Hufnagel, vielen Dank für die Info. Die ist schon bekannt. Die nächsten Wochen wird es an OpenKIM weitergehen. Folgendes wird gemacht:
1. Integration der KAS-API
2. Integration der AM-API, AL-API
3. jede AFO bekommt einen Unit-Test

Wir können uns gerne austauschen.

**Comment by basketmc** [comment]
Hi Dominik, wird mit dem Release 0.16.0 erledigt. Vg, Christian

**Comment by basketmc** [comment]
mit dem heutigen Release erledigt
